### ISSUE TITLE
GPS coordinate filtering

### ISSUE THREAD

**Issue by Ran-snow** [progweb/gpx2video#10]
When i use gpx2video , i find a scene that a part of gps coordinate isn't inaccurate。
Can you filter it out according to certain rules？

**Comment by progweb** [comment]
Hi,

Today, there isn't gps waypoint filter. In waiting, other tools can filter and smooth gpx files.
In futur, gpx2video should be able to filter bad gpx waypoints, but not a segment. Only few points. It should be able to smooth the track and interpolate some points.

That's why I have started to add filter (as kalman) and csv export. But need work again !

**Comment by Ran-snow** [comment]
ok .
